### ISSUE TITLE
undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by wwq66** [irfanICMLL/structure_knowledge_distillation#12]
My environment: pytorch 0.4.1, cudatoolkit 9.0. After run `python build.py`,
when runing train_and_eval.py, I met the mistake.

Traceback (most recent call last):
  File "train_and_eval.py", line 3, in <module>
    from networks.kd_model import NetModel
  File "/data/code/structure_knowledge_distillation-master/networks/kd_model.py", line 21, in <module>
    from networks.pspnet_combine import Res_pspnet, BasicBlock, Bottleneck
  File "/data/code/structure_knowledge_distillation-master/networks/pspnet_combine.py", line 11, in <module>
    from libs import InPlaceABN, InPlaceABNSync
  File "/data/code/structure_knowledge_distillation-master/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNWrapper, InPlaceABNSync, InPlaceABNSyncWrapper
  File "/data/code/structure_knowledge_distillation-master/libs/bn.py", line 15, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/data/code/structure_knowledge_distillation-master/libs/functions.py", line 5, in <module>
    from . import _ext
  File "/data/code/structure_knowledge_distillation-master/libs/_ext/__init__.py", line 3, in <module>
    from .__ext import lib as _lib, ffi as _ffi
ImportError: /data/code/structure_knowledge_distillation-master/libs/_ext/__ext.so: undefined symbol: __cudaPopCallConfiguration

**Comment by xuyanr** [comment]
> My environment: pytorch 0.4.1, cudatoolkit 9.0. After run `python build.py`,
> when runing train_and_eval.py, I met the mistake.
> 
> Traceback (most recent call last):
> File "train_and_eval.py", line 3, in
> from networks.kd_model import NetModel
> File "/data/code/structure_knowledge_distillation-master/networks/kd_model.py", line 21, in
> from networks.pspnet_combine import Res_pspnet, BasicBlock, Bottleneck
> File "/data/code/structure_knowledge_distillation-master/networks/pspnet_combine.py", line 11, in
> from libs import InPlaceABN, InPlaceABNSync
> File "/data/code/structure_knowledge_distillation-master/libs/**init**.py", line 1, in
> from .bn import ABN, InPlaceABN, InPlaceABNWrapper, InPlaceABNSync, InPlaceABNSyncWrapper
> File "/data/code/structure_knowledge_distillation-master/libs/bn.py", line 15, in
> from .functions import inplace_abn, inplace_abn_sync
> File "/data/code/structure_knowledge_distillation-master/libs/functions.py", line 5, in
> from . import _ext
> File "/data/code/structure_knowledge_distillation-master/libs/_ext/**init**.py", line 3, in
> from .__ext import lib as _lib, ffi as _ffi
> ImportError: /data/code/structure_knowledge_distillation-master/libs/_ext/__ext.so: undefined symbol: __cudaPopCallConfiguration

Have you worked out any approach to solve the problem?

**Comment by irfanICMLL** [comment]
It is caused by the sync bn.
Make sure that the cuda version of your cudatookit and the pytorch is the same.
You can refer to this issue.
https://github.com/rusty1s/pytorch_scatter/issues/19

**Comment by xuyanr** [comment]
Thanks for you reply,I have solved this problem, but unfortunately I have encountered another problem, if it is convenient, I hope you can help me to solve this problem, it would be greatly appreciated.
The problem seems to come from /libs/_ext/__init__.py








At 2019-12-09 09:05:16, "yifan liu" <notifications@github.com> wrote:


It is caused by the sync bn.
Make sure that the cuda version of your cudatookit and the pytorch is the same.
You can refer to this issue.
rusty1s/pytorch_scatter#19

**Comment by irfanICMLL** [comment]
Are there any attached picture? I can not find your error information.

**Comment by xuyanr** [comment]
Is that what you need?








At 2019-12-15 15:47:01, "yifan liu" <notifications@github.com> wrote:

Are there any attached picture? I can not find your error information.

**Comment by irfanICMLL** [comment]
Sorry, I can not see the picture. It looks like the following pictures. Maybe you can send me an email about your question.
![Screenshot from 2020-01-07 16-42-06](https://user-images.githubusercontent.com/22712375/71872594-d64fbb80-316c-11ea-954b-3d2fa1f3a194.png)
![Screenshot from 2020-01-07 16-42-02](https://user-images.githubusercontent.com/22712375/71872595-d6e85200-316c-11ea-9b0d-12b0860d6e9f.png)

**Comment by irfanICMLL** [comment]
yifan.liu04@adelaide.edu.au
