### ISSUE TITLE
Teacher Model

### ISSUE THREAD

**Issue by Vincent-Hoo** [irfanICMLL/structure_knowledge_distillation#15]
Can you provide the teacher model trained on cityscapes?

**Comment by irfanICMLL** [comment]
Please refer to this issue https://github.com/irfanICMLL/structure_knowledge_distillation/issues/4

**Comment by Vincent-Hoo** [comment]
Thank you very much!! I have another question about loading pretrained resnet to PSPNet. The lower part of PSPNet is slightly different from that of ResNet. PSPnet has three layers of {conv, relu, bn} while ResNet only has one layer. Did you re-train the new-ResNet (with 3 {conv, relu, bn} layers) in ImageNet dataset. I've checked the "load_S_model" function, and in the "conv1.weight" module, there's a dimension dismatch.

**Comment by irfanICMLL** [comment]
For the teacher net I follow this link, and use the pretrained weight it provides.

https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/models/resnet.py
