### ISSUE TITLE
Log file of training 

### ISSUE THREAD

**Issue by amirassov** [irfanICMLL/structure_knowledge_distillation#17]
Hi, I am trying to reproduce this code. Can you provide the model training logs on cityscapes?

**Comment by irfanICMLL** [comment]
I have already sent the log to you by your gmail. Please check.

**Comment by irfanICMLL** [comment]
If you do not mind, I will close this issue.

**Comment by ArsenLuca** [comment]
@irfanICMLL would you please send me a copy?Thank you very much
