### ISSUE TITLE
Environment issues

### ISSUE THREAD

**Issue by SanthoshRajendiran** [irfanICMLL/structure_knowledge_distillation#19]
Hi, I am new to pytorch. And I am facing some issues related to imports, when trying to execute and test your script as it is. I feel those import issues, are purely based on some torch version issues. I am using Ubuntu 16.04. Can you share your requirements.txt file, so that I can install those packages, and test out the script in my machine.

**Comment by irfanICMLL** [comment]
Requirement
python3.5

pytorch0.4.1

ninja

numpy

cv2

Pillow

We recommend to use Anaconda.
