### ISSUE TITLE
nan loss value

### ISSUE THREAD

**Issue by sungsooo** [irfanICMLL/structure_knowledge_distillation#25]
Hi, I have a problem while training your project.
I just clone your repo, and only changed the data path.

But, when I train with PI + PA + HO losses, the loss became nan value after several steps.
I used the teacher weights you provide, trained the student net from scratch.
Can you advise to reproduce your paper?
If you don't mind, can you share your log file?

Thank you.

**Comment by irfanICMLL** [comment]
Please checkout this branch: d1ec858edc25e2671e9a15d5fda4628b9fdbf48b
It will fix the nan problem.

**Comment by sungsooo** [comment]
Thank you for your reply!
I want to know the difference between the two branches.
Could you explain why the master branch has occurred the nan problem?
Thank you!

**Comment by sungsooo** [comment]
Hi,
I’m trying to reproduce your knowledge distillation method.

As you mentioned, I clone the d1ec858
<https://github.com/irfanICMLL/structure_knowledge_distillation/commit/d1ec858edc25e2671e9a15d5fda4628b9fdbf48b>
branch.
But I cant reproduce your results.

I followed the compiling instructions.
Then I just modified the cityscapes data path and downloaded the teacher
net you uploaded.
When I evaluated the teacher net with cityscapes, the teacher net got about
75.79 mIoU, which is does not match with your paper mIoU 78.56.
With the teacher net, I just executed the run_train_val.sh with PI, PA, HO
losses.
But I can’t reproduce your results.
It had occurred nan loss value after some iterations.
Could you help me?
Could you share your log file for reference?

Thank you.
Regards.

2020년 4월 20일 (월) 오후 3:54, yifan liu <notifications@github.com>님이 작성:

**Comment by irfanICMLL** [comment]
We have employed an unstable form of KL divergence. We will fix this bug recently. But the old branch can also have promising results for distillation.

**Comment by wuzhiyang2016** [comment]
hello, is checkout to master branch?
