### ISSUE TITLE
D_loss becomes NAN during training

### ISSUE THREAD

**Issue by zhouzg** [irfanICMLL/structure_knowledge_distillation#28]
Hi, I meet a problem during training：**D_loss becomes NAN** 
I have tried several times and the problem always appears at around 2600 steps.
![image](https://user-images.githubusercontent.com/40598644/83347823-4e0bc600-a35a-11ea-8627-8df6084edb17.png)
I have loaded the teacher ckpt and I only changed **data-dir** and **batch-size**(from 8 to 6 since limited by memory) in "run_train_val.sh" .

[issue25](https://github.com/irfanICMLL/structure_knowledge_distillation/issues/25 ) seems to meet a similar problem. But I can't find branch d1ec858 mentioned in that issue.

Could you please give me some advice? 
Thank you! and Best wishes!

**Comment by irfanICMLL** [comment]
git clone all the code, and then git checkout d1ec858
You will find that branch.

**Comment by zhouzg** [comment]
Thanks for your reply! I have found it.

**Comment by DHuiTnut** [comment]
Hello! I changed the batchsize from 8 to 4  becaouse the limit of my gpu memory. Then I came across NAN.
And I have tried git checkout d1ec858,  but the pixelwise loss never decreased.
![image](https://user-images.githubusercontent.com/43811941/101710231-0796e100-3acc-11eb-8d9c-22bd4d2c251b.png)
Can you please tell me how to deal with this problem? Thank you so much.
