### ISSUE TITLE
I can't get your mIoU on cityscapes dataset.

### ISSUE THREAD

**Issue by mailhoho** [irfanICMLL/structure_knowledge_distillation#29]
Hi, I trained your script PSPNet-resnet18. (student baseline)
But, I can't get refered on paper mIoU(69.10%)

When I trained the student network, is_pi_use, is_pa_use and is_ho_use parameters are False.
I used ImageNet pretrined weight except conv1, conv2, conv3 and layer1.0.conv.

How to train for reaching your mIoU?

My environments are
Ubuntu 16.04
Pytorch-0.4.1.post2
Python 3.5.6

thanks

**Comment by irfanICMLL** [comment]
You may get around 68 using the new version of the training code.

**Comment by irfanICMLL** [comment]
The distillation results will be the same as our paper.

**Comment by xuyuxiu83** [comment]
> Hi, I trained your script PSPNet-resnet18. (student baseline) But, I can't get refered on paper mIoU(69.10%)
> 
> When I trained the student network, is_pi_use, is_pa_use and is_ho_use parameters are False. I used ImageNet pretrined weight except conv1, conv2, conv3 and layer1.0.conv.
> 
> How to train for reaching your mIoU?
> 
> My environments are Ubuntu 16.04 Pytorch-0.4.1.post2 Python 3.5.6
> 
> thanks

hello，I cannot enter the website of the pretrained model now.Could you please share it with me?My email is xuyuxiu83@gmail.com.
