### ISSUE TITLE
ESPNet training

### ISSUE THREAD

**Issue by sungsooo** [irfanICMLL/structure_knowledge_distillation#32]
Hi,
I want to reproduce the ESPNet KD performance.
So, I just want to know how did you train the ESPNet?

Did you use the same res101-pspnet as the teacher net?

Which features were used for the pi, pa, ho loss?
Thank you

**Comment by irfanICMLL** [comment]
Yes. I use re101 as the teacher net. For ESP-C it is the same as present 18. I use the feature at 8x resolution.
For ESP, I add at the 8x feature in the middle. Therefore, the improvements are not as good as ECP-C.

**Comment by betogulliver** [comment]
I'd also like to reproduce the results using ESPNet, any ideas on how to proceed? 
I guess I need to adapt "networks/pspnet_combine.py" for ESPNet.
Am I'm on the right track? (can you share your steps?)

thanks for any/all help.
