### ISSUE TITLE
codes for PAMI version

### ISSUE THREAD

**Issue by ArsenLuca** [irfanICMLL/structure_knowledge_distillation#33]
Hi @irfanICMLL , would you please update the codes for extensions in PAMI version?

**Comment by irfanICMLL** [comment]
In the PAMI  version, we apply the distillation to FCOS and VNL. Both of them have released code. We release the base module for distillation, you can apply the distillation to those tasks.

**Comment by frischzenger** [comment]
can you share the link of FCOS and VNL codes?
