### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by wl082013** [irfanICMLL/structure_knowledge_distillation#36]
Hi , 
I am running your code according to the instructions of installing relevant libraries.
However, I failed to built the '__ext',  and I continuously encountered the error  ' no such a from .__ext import lib as _lib, ffi as _ffi'.
I think my GPU setting is correct and I installed torch 0.4.1 and use gencode=arch=compute_61,code=sm_61 for 1080 Ti GPU. 
However, there is an error, and I don't know how to solve  this problem, could you provide a help? 
Thanks 
![image](https://user-images.githubusercontent.com/16892862/87387492-cca48600-c5dd-11ea-80bd-12e957d1dca3.png)

**Comment by irfanICMLL** [comment]
It means you have multiple environments. Please make a clean environment and follow the instructions.

**Comment by RonDen** [comment]
Hi, I have encountered the same problems, can you give me some detail on how to solve this?
I have tried to create a new conda evironment with python=3.5, torch==0.4, and successfully build the bn.o and __ext.so files.
But when I use command `python test`, I got the same error.
I tried to delete the __ext.so file and rebuild, but the same error again and again.

What you mean about the `multiple environments`, and how to `clean the environment`?
