### ISSUE TITLE
Can you provide the ResNet(1.0) baseline train log?

### ISSUE THREAD

**Issue by aye0804** [irfanICMLL/structure_knowledge_distillation#39]
I have trained ResNet(1.0) baseline without ImN and the result is 0.513.  I can't reproduce the Baseline without ImN 0.575 in the paper.

**Comment by irfanICMLL** [comment]
Have you used this script?
https://github.com/irfanICMLL/structure_knowledge_distillation/blob/cvpr_19/network/student_res18.py
It is a little different from the official resnet18.
