### ISSUE TITLE
Can you share your teacher's weight ?

### ISSUE THREAD

**Issue by idealwei** [irfanICMLL/structure_knowledge_distillation#4]
Nice work. Can you share your teachers' weight used in your segmentation distillation ? It will be very helpful for better re-implementation.

**Comment by irfanICMLL** [comment]
https://cloudstor.aarnet.edu.au/plus/s/tFjYfBJiarVi0pG
The weights for the teacher net can be download through this link.
 For depth estimation and object detection, we just use the weight the author released
