### ISSUE TITLE
no models for detection and depth estimation

### ISSUE THREAD

**Issue by wl082013** [irfanICMLL/structure_knowledge_distillation#40]
Hi, 
I am wondering about the implementation of detection and depth estimation, 
could you please provide the relevant codes? 
Thanks

**Comment by irfanICMLL** [comment]
I have modified the official code of VNL and FCOS, using the loss provided in the CVPR version. Please see the README. I also provided the trained model for these tasks.

Recently I have been working on a distillation toolbox with detectron2. I will release it after I finished.

**Comment by wl082013** [comment]
okay thanks, I am modifying the code for detection using yolov3,  but I am not sure about the loss functions.

**Comment by irfanICMLL** [comment]
You can refer to this issue: https://github.com/irfanICMLL/structure_knowledge_distillation/issues/27

He has reproduced the results successfully.
