### ISSUE TITLE
Why the patch size turn out to be half of the original feature map size in CriterionPairWiseforWholeFeatAfterPool?

### ISSUE THREAD

**Issue by Ssssseason** [irfanICMLL/structure_knowledge_distillation#51]
Table 2 shows it performs best when beta=2x2. 
But in `run_train_val.sh`, `pool-scale` is 0.5, thus finally in `CriterionPairWiseforWholeFeatAfterPool`, the patch size is half of the original feature map size, not 2x2.

**Comment by DHuiTnut** [comment]
[issue31](https://github.com/irfanICMLL/structure_knowledge_distillation/issues/31) might be the answer

**Comment by Ssssseason** [comment]
> [issue31](https://github.com/irfanICMLL/structure_knowledge_distillation/issues/31) might be the answer

Not the same question. That issue is about alpha, but what I concern about is the value of beta

**Comment by irfanICMLL** [comment]
Beta 2*2 means we use feature maps in 2*2 areas as one node. It is implemented by pooling with 0.5.
