### ISSUE TITLE
Puzzled about this loop

### ISSUE THREAD

**Issue by NickChang97** [irfanICMLL/structure_knowledge_distillation#52]
https://github.com/irfanICMLL/structure_knowledge_distillation/blob/f6e6565ddfb910d1aec477b34e58d79e097b339e/eval_esp.py#L188
Thanks for your code. I have something puzzling about this.
Is your code indent below this loop right. If it is. Why just use  "flag = c_keys[-1].split('.')[0]" instead

**Comment by irfanICMLL** [comment]
You are correct. You can use it instead.
