### ISSUE TITLE
Could you please provide teacher model?

### ISSUE THREAD

**Issue by wheatjo** [irfanICMLL/structure_knowledge_distillation#7]
Your work is amazing. But when i try to use your teacher model to train, i haven't find your teacher model "./ckpt/Teacher/CS_scenes_38413_0.7832174615268139.pth".

**Comment by irfanICMLL** [comment]
[https://github.com/irfanICMLL/structure_knowledge_distillation/issues/4](url)

**Comment by irfanICMLL** [comment]
https://cloudstor.aarnet.edu.au/plus/s/tFjYfBJiarVi0pG
The weights for the teacher net can be download through this link.
