### ISSUE TITLE
I need some help from you..

### ISSUE THREAD

**Issue by WBS-123** [irfanICMLL/structure_knowledge_distillation#8]
from .__ext import lib as _lib, ffi as _ffi
i can't find the ._ext/lib and ._ext/ffi
this error arise: No module named 'libs._ext._ext'
could you fix the problem for me?

**Comment by irfanICMLL** [comment]
Have you compiled the inplaceABN before using the code?

### Compiling

Some parts of InPlace-ABN have a native CUDA implementation, which must be compiled with the following commands:
```bash
cd libs
sh build.sh
python build.py
``` 
The `build.sh` script assumes that the `nvcc` compiler is available in the current system search path.
The CUDA kernels are compiled for `sm_50`, `sm_52` and `sm_61` by default.
To change this (_e.g._ if you are using a Kepler GPU), please edit the `CUDA_GENCODE` variable in `build.sh`.

**Comment by irfanICMLL** [comment]
I will close this issue. You can contact me if you have any other questions.

**Comment by wangq95** [comment]
@irfanICMLL Hi, I complied the InPlaceABN but got an error "ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead." when I try to run 'python build.py', the pytorch version is 1.5.0.
